var Mes;
(function (Mes) {
    Mes[Mes["JANEIRO"] = 0] = "JANEIRO";
    Mes[Mes["FEVEREIRO"] = 1] = "FEVEREIRO";
    Mes[Mes["MARCO"] = 2] = "MARCO";
    Mes[Mes["ABRIL"] = 3] = "ABRIL";
    Mes[Mes["MAIO"] = 4] = "MAIO";
    Mes[Mes["JUNHO"] = 5] = "JUNHO";
    Mes[Mes["JULHO"] = 6] = "JULHO";
    Mes[Mes["AGOSTO"] = 7] = "AGOSTO";
    Mes[Mes["SETEMBRO"] = 8] = "SETEMBRO";
    Mes[Mes["OUTUBRO"] = 9] = "OUTUBRO";
    Mes[Mes["NOVEMBRO"] = 10] = "NOVEMBRO";
    Mes[Mes["DEZEMBRO"] = 11] = "DEZEMBRO";
})(Mes || (Mes = {}));
var pedido = "Pizza";
var numeroPedido = 1234;
var pedidoConfirmado = true;
var listaFrutas = ["abacaxi", "kiwi", "maçã", "abacate", "uva"];
var pessoa = { nome: "Alexandre", idade: 30, rg: "000000000000", cpf: "000000000000" };
var teste = "teste";
var dados = 123;
var mouseEvent;
var mostrarMensagem = function (value) { return console.log(value); };
console.log(pedido);
console.log(numeroPedido);
console.log(pedidoConfirmado);
mostrarMensagem("Hello world!");
mostrarMensagem("1, 2, 3 testando.");
mostrarMensagem(369);
console.log(listaFrutas);
console.log(pessoa);
console.log(teste);
console.log(dados);
console.log(Mes);
